### ISSUE TITLE
If this feature is combined with the following software, it will be invincible

### ISSUE THREAD

**Issue by whaty** [smaranjitghose/QueryKing#1]
https://github.com/www-zerocode-net-cn/ERD-Online

**Comment by smaranjitghose** [comment]
I would need to check the codebase but open to a merger

**Comment by whaty** [comment]
我这里有一些已经实现的用法，有空可以看下 https://mp.weixin.qq.com/s?__biz=Mzg4MjkwMTA3NQ==&mid=2247484470&idx=1&sn=0461f0a92308f48218dd4a55200bf6b2&chksm=cf4eed0af839641c3870c0031907db6ea8bc99440611a2e90ac9c7d0693c9d92e7ef1c430b3f#rd
